version: '3.8'
services:
    floodalert-backend:
      build:
        context: .
        dockerfile: Dockerfile
      volumes: 
        - .:/app
      ports: 
        - 8000:8000
      depends_on: 
        - postgres

    postgres:
      image: postgres:alpine
      environment:
        POSTGRES_DB: flood
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /tmp
      volumes:
        - ./storage/postgresql:/var/lib/postgresql
      ports:
        - 5432:5432